import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "./provider/AuthProvider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={" h-full antialiased"}
    >
      <body className="min-h-screen bg-slate-950 text-slate flex flex-col">
        <AuthProvider>

        {children}
        </AuthProvider>
        </body>
    </html>
  );
}
